import React, { useState, useCallback } from 'react';
import { generateJoke } from './geminiService.ts';
import { Vibe, GeneratorState } from './types.ts';
import { JokeCard } from './components/JokeCard.tsx';
import { VibeSelector } from './components/VibeSelector.tsx';

const App: React.FC = () => {
  const [state, setState] = useState<GeneratorState>({
    joke: null,
    loading: false,
    error: null,
    vibe: Vibe.SURPRISE
  });

  const fetchJoke = useCallback(async () => {
    setState(prev => ({ ...prev, loading: true, error: null }));
    try {
      const newJoke = await generateJoke(state.vibe);
      setState(prev => ({ ...prev, joke: newJoke, loading: false }));
    } catch (err: any) {
      setState(prev => ({ ...prev, loading: false, error: err.message }));
    }
  }, [state.vibe]);

  const setVibe = (newVibe: Vibe) => {
    setState(prev => ({ ...prev, vibe: newVibe }));
  };

  const shareJoke = async () => {
    if (!state.joke) return;
    const text = `${state.joke.setup}\n\n${state.joke.punchline}\n\nGenerated by GiggleGlitch ✨`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'GiggleGlitch Joke',
          text: text,
        });
      } catch (err) {
        console.error('Share failed:', err);
      }
    } else {
      navigator.clipboard.writeText(text);
      alert('Copied to clipboard! Go share the glitch.');
    }
  };

  return (
    <div className="min-h-screen relative flex flex-col items-center justify-center p-6 sm:p-12 overflow-hidden">
      {/* Background Ambience */}
      <div className="fixed inset-0 pointer-events-none -z-10">
        <div className="absolute top-[-10%] left-[-10%] w-[50vw] h-[50vh] bg-violet-900/20 blur-[150px] rounded-full"></div>
        <div className="absolute bottom-[-10%] right-[-10%] w-[50vw] h-[50vh] bg-blue-900/10 blur-[150px] rounded-full"></div>
        <div className="absolute top-[30%] left-[20%] w-[30vw] h-[30vh] bg-pink-900/10 blur-[120px] rounded-full animate-pulse"></div>
      </div>

      <header className="text-center mb-10 relative z-10 animate-in fade-in slide-in-from-top-4 duration-1000">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-violet-500/10 border border-violet-500/20 text-violet-300 text-[10px] font-bold tracking-[0.2em] uppercase mb-6">
          <span className="w-2 h-2 bg-violet-500 rounded-full animate-ping"></span>
          Neural Happiness Engine v3
        </div>
        <h1 className="text-6xl md:text-8xl font-display font-extrabold text-white mb-4 tracking-tighter leading-none text-glow">
          Giggle<span className="text-transparent bg-clip-text bg-gradient-to-r from-violet-400 via-pink-400 to-violet-500">Glitch</span>
        </h1>
        <p className="text-slate-400 text-lg md:text-xl max-w-md mx-auto leading-relaxed font-light">
          Short-circuit your stress with precision-engineered AI humor.
        </p>
      </header>

      <main className="w-full flex flex-col items-center space-y-12 relative z-10">
        <VibeSelector currentVibe={state.vibe} onVibeChange={setVibe} />

        <JokeCard joke={state.joke} loading={state.loading} />

        {state.error && (
          <div className="px-6 py-3 bg-rose-500/10 border border-rose-500/20 rounded-2xl text-rose-400 text-sm font-medium animate-bounce">
            ⚠️ {state.error}
          </div>
        )}

        <div className="flex flex-col sm:flex-row gap-4 items-center w-full max-w-sm">
          <button
            onClick={fetchJoke}
            disabled={state.loading}
            className="w-full group relative px-8 py-5 bg-white text-slate-950 font-black rounded-[2rem] hover:scale-[1.02] active:scale-95 transition-all duration-300 disabled:opacity-50 disabled:scale-100 flex items-center justify-center gap-3 shadow-[0_20px_60px_-15px_rgba(139,92,246,0.5)] overflow-hidden"
          >
            <div className="absolute inset-0 bg-gradient-to-r from-transparent via-violet-200/50 to-transparent translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-1000"></div>
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className={`${state.loading ? 'animate-spin' : 'group-hover:rotate-[30deg] transition-transform duration-500'}`}>
              <path d="M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8"></path>
              <path d="M21 3v5h-5"></path>
            </svg>
            <span className="uppercase tracking-widest text-sm glitch-hover">
              {state.joke ? 'Another Glitch' : 'Initiate Session'}
            </span>
          </button>

          {state.joke && !state.loading && (
            <button
              onClick={shareJoke}
              className="px-6 py-5 glass text-white rounded-[2rem] hover:bg-white/10 active:scale-95 transition-all flex items-center gap-3 border-white/5 whitespace-nowrap"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"></path>
                <polyline points="16 6 12 2 8 6"></polyline>
                <line x1="12" y1="2" x2="12" y2="15"></line>
              </svg>
              Share
            </button>
          )}
        </div>
      </main>

      <footer className="mt-16 text-slate-600 text-[10px] font-bold tracking-[0.4em] uppercase relative z-10 flex flex-col items-center gap-2">
        <div className="w-12 h-[1px] bg-slate-800"></div>
        <span>Powered by Gemini 3 Flash • Built for Smiles</span>
      </footer>
    </div>
  );
};

export default App;